"""Vendor-neutral document and workflow classifications."""

from __future__ import annotations

from enum import Enum


class SourceFormat(str, Enum):
    IMAGE = "IMAGE"
    PDF_TEXT = "PDF_TEXT"
    PDF_SCAN = "PDF_SCAN"
    DOCX = "DOCX"
    XLSX = "XLSX"
    PPTX = "PPTX"
    LEGACY_DOC = "LEGACY_DOC"
    LEGACY_XLS = "LEGACY_XLS"
    UNKNOWN = "UNKNOWN"


class DocumentType(str, Enum):
    CV = "CV"
    EMPLOYEE_PROFILE = "EMPLOYEE_PROFILE"
    IDENTITY_CARD = "IDENTITY_CARD"
    PASSPORT = "PASSPORT"
    EMPLOYMENT_CONTRACT = "EMPLOYMENT_CONTRACT"
    CONTRACT_APPENDIX = "CONTRACT_APPENDIX"
    HR_DECISION = "HR_DECISION"
    LEAVE_REQUEST = "LEAVE_REQUEST"
    OVERTIME_REQUEST = "OVERTIME_REQUEST"
    BUSINESS_TRIP_REQUEST = "BUSINESS_TRIP_REQUEST"
    TIMESHEET = "TIMESHEET"
    PAYROLL = "PAYROLL"
    CERTIFICATE = "CERTIFICATE"
    DEGREE = "DEGREE"
    INTERNAL_POLICY = "INTERNAL_POLICY"
    OFFICIAL_DISPATCH = "OFFICIAL_DISPATCH"
    ADMINISTRATIVE_FORM = "ADMINISTRATIVE_FORM"
    UNKNOWN = "UNKNOWN"


class WorkflowType(str, Enum):
    ONBOARDING = "ONBOARDING"
    EMPLOYEE_RECORD_MANAGEMENT = "EMPLOYEE_RECORD_MANAGEMENT"
    CONTRACT_MANAGEMENT = "CONTRACT_MANAGEMENT"
    LEAVE_MANAGEMENT = "LEAVE_MANAGEMENT"
    TIMESHEET_REVIEW = "TIMESHEET_REVIEW"
    PAYROLL_PREPARATION = "PAYROLL_PREPARATION"
    TRAINING_AND_CERTIFICATION = "TRAINING_AND_CERTIFICATION"
    OFFICIAL_DOCUMENT_PROCESSING = "OFFICIAL_DOCUMENT_PROCESSING"
    UNKNOWN = "UNKNOWN"


class ParseStatus(str, Enum):
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    CONVERSION_REQUIRED = "CONVERSION_REQUIRED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class WarningSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
